title: Nabhit Arorra
logo: /assets:img/circle_headshot.png
description: Currently a Junior at Penn State University, seeking an internship or a part-time position utilizing programming, and computational skills.
LinkedIn: [Connect with me on LinkedIn](https://www.linkedin.com/in/nabhitarora/)
#show_downloads: true
theme: jekyll-theme-minimal
