title: Nabhit Arorra
#logo: /assets/img/headshot_circle.png
description: Currently a Junior at Penn State University, seeking an internship or a part-time position utilizing programming, and computational skills.
show_downloads: true
theme: jekyll-theme-minimal
