title: Nabhit Arorra
logo: /assets:img/circle_headshot.png
[Connect with me on LinkedIn](https://www.linkedin.com/in/nabhitarora/)
description: Currently a Junior at Penn State University, seeking an internship or a part-time position utilizing programming, and computational skills.
show_downloads: true
theme: jekyll-theme-minimal
